# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YI0RtMdG21XufZg-jD1Uzx47lfVBsVRi
"""

# -*- coding: utf-8 -*-
"""Assignment-4.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1QLgolGDxpC5slk5p3tlwNVThAIhm096o
"""

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np


#if using termux
import subprocess
import shlex
#end if

#creating x,y for 3D plotting
xx, yy = np.meshgrid([-10,10], range(10))
#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')


#defining planes:  n.T * x = c 
n1 = np.array([0.285714286,0.428571429,0.571428571])
a =  np.array([2,5,-3])
b = np.array([-2,-3,5])
c = np.array([5,3,-3])
c1 = 7

#corresponding z for planes
z1 = (c1-n1[0]*xx-n1[1]*yy)/(n1[2])

#plotting planes
Plane=ax.plot_surface(xx, yy, z1,label="Plane", color='b',alpha=0.50)
Plane._facecolors2d=Plane._facecolors3d
Plane._edgecolors2d=Plane._edgecolors3d
#plotting point
ax.scatter(A[0],A[1],A[2],'o')
ax.text(2.2,5.2,-3.2,'a')
ax.text(-2.2,-3.2,5.2,'b')
ax.text(5.2,3.2,-3.2,'c')

#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend(loc='best');plt.grid()